### ISSUE TITLE
Can I contribute?

### ISSUE THREAD

**Issue by jsuarezruiz** [FormsCommunityToolkit/Animations#2]
Hello everyone,

I have a animation library used in some projects and demos: [https://github.com/jsuarezruiz/Xamanimation](https://github.com/jsuarezruiz/Xamanimation)
It has Behaviors, Triggers and extensions to allow to launch customized animations in a simple way from XAML and C #.

Currently I am adding new animations (ColorAnimation) and types (lists animations) :)

Could interest as a contribution?

**Comment by jamesmontemagno** [comment]
We have decided not to do animations right now.
